name: 90min Odds Scan
on:
  schedule:
    - cron: '0 */2 * * *'
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with:
          token: ${{ secrets.MY_TOKEN }}

      - name: Fetch API Data
        run: |
          curl "https://api.the-odds-api.com/v4/sports/soccer_epl/odds/?apiKey=8d79681b1e42354408fb13d12b34887d&regions=eu&markets=h2h" -o public/data.json
          # Kopiramo ga i u root radi sigurnosti GitHub Pages-a
          cp public/data.json data.json
          
      - name: Commit and Push Data
        run: |
          git config --global user.name "GitHub Action"
          git config --global user.email "action@github.com"
          git add public/data.json data.json
          git commit -m "Automated Odds Update" || exit 0
          git push
